- name: YUM installing system python3 as required by Glances
  yum:
    name:
      - python3
      - python3-devel
      - python3-pip
      - python3-setuptools
    state: present

- name: PIP3 installing Glances and its modules dependences
  pip:
    executable: /usr/bin/pip3
    name:
      - netifaces
      - pySMART
      - pymdstat
      - py3nvml
      - py-cpuinfo
      - glances
    state: present
  notify: restart glances

- name: GLANCES copying glances.service script to systemd dir
  template:
    src: glances.service.j2
    dest: /etc/systemd/system/glances.service
    owner: root
    group: root
    mode: 0644

- name: GLANCES creating /etc/glances dir
  file: path=/etc/glances state=directory mode=0755

- name: GLANCES deploying glances.conf from template profile
  template:
    src: glances.conf.{{ mon_glances_conf_profile }}.j2
    dest: /etc/glances/glances.conf
    owner: root
    group: root
    mode: 0644
  notify: restart glances

- name: SYSTEMD enabling and starting Glances as a systemd service
  systemd:
    name: glances
    enabled: yes
    state: started
