- name: YUM install OMSA (srvadmin-all)
  yum:
    name:
      - srvadmin-all
    state: present
    update_cache: yes
  register: yum_rc
  retries: 10
  until: yum_rc is succeeded
  delay: 5

- name: OMSA services restart (srvadmin-services)
  shell: "/opt/dell/srvadmin/sbin/srvadmin-services.sh restart"
  changed_when: false
  ignore_errors: true

