---
- hosts: localhost
  vars:
    service: "ZEPPELIN"
    ambari_component: "ZEPPELIN_MASTER"
    config_name: "zeppelin-shiro-ini"
    target_service_host: 
    command:
    context:
    state: 
    body_request_service_change_config:
      Clusters:
        desired_config:
          type: "{{ config_name }}"
          tag: "{{ ansible_date_time.iso8601 }}"
          properties:
            shiro_ini_content: "{{ lookup('file', '/home/lmansop/{{ config_name }}.config') }}"
    body_request_command:
      RequestInfo:
        command: "{{ command }}"
        context: "{{ context }}"
        operation_level:
          level: "SERVICE"
          cluster_name: "{{ cluster }}"
          service_name: "{{ service }}"
      Requests/resource_filters:
        - service_name: "{{ service }}"
          component_name: "{{ ambari_component }}"
          hosts: "{{ target_service_host }}"
  tasks:
    - name: update service config
      uri:
        url: "http://{{ ambari_api_host }}:{{ 8080 }}/api/v1/clusters/{{ cluster }}"
        user: admin
        password: admin
        force_basic_auth: yes
        method: put
        headers: {Cookie: "AMBARISESSIONID=node017c6u8hjkbp8513wc6v2f263e6111.node0", X-Requested-By: 'ANSIBLE SCRIPT'}
        body: "{{ body_request_service_change_config | to_json }}"
    - set_fact:
        command: "{{ command_restart }}"
        context: "AMBARI - restart service {{ service }}"
        target_service_host: "{{ zeppelin_host }}"
    - name: restart service
      uri:
        url: "http://{{ ambari_api_host }}:{{ 8080 }}/api/v1/clusters/{{ cluster }}/requests"
        status_code: 
          - 202
          - 200
        user: admin
        password: admin
        force_basic_auth: yes
        method: post
        headers: {Cookie: "AMBARISESSIONID=node017c6u8hjkbp8513wc6v2f263e6111.node0", X-Requested-By: 'ANSIBLE SCRIPT'}
        body: "{{ body_request_command | to_json }}"
