---
- hosts: localhost
  vars:
    cluster: "Garndline"
    service: "ZEPPELIN"
    ambari_api_host: 10.0.1.245
    ambari_api_port: 8080
    ambari_component: "ZEPPELIN_MASTER"
    state_start: "STARTED"
    state_stop: "INSTALLED"
    state: 
    cluster: "Grandline"
    config_name: "zeppelin-shiro-ini"
    body_request_service_change_config:
      Clusters:
        desired_config:
          type: "{{ config_name }}"
          tag: "{{ ansible_date_time.iso8601 }}"
          properties:
            shiro_ini_content: "{{ lookup('file', '/home/lmansop/zeppelin-shiro-ini.config') }}"
    body_request_service_state:
      ServiceComponentInfo:
        state: "{{ state }}"
  tasks:
    - name: update service config
      uri:
        url: "http://{{ ambari_api_host }}:{{ 8080 }}/api/v1/clusters/{{ cluster }}"
        user: admin
        password: admin
        force_basic_auth: yes
        method: put
        headers: {Cookie: "AMBARISESSIONID=node017c6u8hjkbp8513wc6v2f263e6111.node0", X-Requested-By: 'ANSIBLE SCRIPT'}
        body: "{{ body_request_service_change_config | to_json }}"
    - set_fact:
        state: "{{ state_stop }}"
    - name: stop ambari service
      uri:
        url: "http://{{ ambari_api_host }}:{{ 8080 }}/api/v1/clusters/{{ cluster }}/services/{{ service }}/components/{{ ambari_component }}"
        status_code: 
          - 200
          - 202
        user: admin
        password: admin
        force_basic_auth: yes
        method: put
        headers: {Cookie: "AMBARISESSIONID=node017c6u8hjkbp8513wc6v2f263e6111.node0", X-Requested-By: 'ANSIBLE SCRIPT'}
        body: "{{ body_request_service_state | to_json }}"
    - set_fact:
        state: "{{ state_start }}"
    - name: start ambari service
      uri:
        url: "http://{{ ambari_api_host }}:{{ 8080 }}/api/v1/clusters/{{ cluster }}/services/{{ service }}/components/{{ ambari_component }}"        
        status_code: 
          - 200
          - 202
        user: admin
        password: admin
        force_basic_auth: yes
        method: put
        headers: {Cookie: "AMBARISESSIONID=node017c6u8hjkbp8513wc6v2f263e6111.node0", X-Requested-By: 'ANSIBLE SCRIPT'}
        body: "{{ body_request_service_state | to_json }}"

