---
- hosts: localhost
  vars:
    cookie_session: {Cookie: "AMBARISESSIONID=node017c6u8hjkbp8513wc6v2f263e6111.node0"}
  tasks:
    - name: update ambari config
      uri:
        url: http://10.0.1.245:8080/api/v1/clusters/Grandline
        user: admin
        password: admin
        force_basic_auth: yes
        headers: {Cookie: 'AMBARISESSIONID=node017c6u8hjkbp8513wc6v2f263e6111.node0', X-Requested-By: 'X-Requested-By'}
        body: "{{ lookup('file', '/home/lmansop/http_body.payload') }}"
