- name: Install jdk8
  yum:
    name:
      - java-1.8.0-openjdk-devel
    state: present
- name: Check if ambari-agent is installed
  command: /bin/rpm -q ambari-agent
  register: rpm_ambari
  changed_when: false
  ignore_errors: true
  
- name: Preparing Hortonworks ambari repos
  template: src=ambari.repo.{{ amb_ver }}.j2 dest=/etc/yum.repos.d/ambari.repo
            owner=root group=root mode=0644
  when: rpm_ambari.stdout.find('is not installed') != -1
  become: true  
- name: Installing the ambari-agent manually
  yum:
    name:
      - ambari-agent
    state: present
  become: true
- name: Configure ambari-agent from template ini
  template: src=ambari-agent.ini.{{ Info_ClusterName }}.j2 dest=/etc/ambari-agent/conf/ambari-agent.ini
            owner=root group=root mode=0644
  notify: restart ambari-agent
            
- name: Deploy ambari host scripts to /etc/ambari-agent/conf/ dir
  template: src={{ item }} dest=/etc/ambari-agent/conf/{{ item | basename | regex_replace('\.j2','') }}
            owner=root group=root mode=0744
  with_fileglob:
    - ../templates/ambari_host_scripts/*.j2
