- debug:
    msg: "DICE VLAN interface {{ dice_vlan_8021q_trunk_dev }}.{{ dice_vlans[item.vlan].id }} {{ item.ip }}"
  with_items: "{{ dice_vlan_8021q_ips }}"

- name: KERNEL MOD add the 801.1Q module
  modprobe:
    name: 8021q
    state: present

- name: DICE VLAN 802.1Q tagging trunk/parent interface ifcfg deploy
  template:
    src: ifcfg-trunk-dev.8021q_tagging.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-{{ dice_vlan_8021q_trunk_dev }}
    owner: root
    group: root
    mode: 0644
  notify: restart network

- name: DICE VLAN 802.1Q tagging VLAN interface ifcfg deploy
  template:
    src: ifcfg-vlan-dev.8021q_tagging.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-{{ dice_vlan_8021q_trunk_dev }}.{{ dice_vlans[item.vlan].id }}
    owner: root
    group: root
    mode: 0644
  with_items: "{{ dice_vlan_8021q_ips }}"
  notify: restart network
