- name: YUM install lldp package
  yum: name=lldpad state=present

- name: LLDP enable as a serice
  service:
    name: lldpad
    state: started
    enabled: yes 

- name: LLDP get the list of target devices from a cmd
  shell: "{{ dice_lldp_dev_cmd }}"
  register: lldp_dev
  changed_when: false

#
# The register variable still get modified/override even
# the task is conditionally skipped. Store the output in
# a separated variable, it will be accessed and assigned
# by set_fact accordingly.
#
- name: LLDP get the list of target devices from file
  command: cat "{{ dice_lldp_dev_file }}"
  register: lldp_dev_from_file
  when: dice_lldp_dev_file is defined
  changed_when: false

- set_fact:
    lldp_dev: "{{ lldp_dev_from_file }}"
  when: dice_lldp_dev_file is defined

- debug:
    msg: "{{ lldp_dev }}"

- name: LLDP apply lldp config on each given interface
  script: config_nic_lldp.sh {{ item }}
  register: script_result
  changed_when: "script_result.rc == 0"
  failed_when: "script_result.rc == -1"
  with_items:
    - "{{ lldp_dev.stdout_lines }}"
