- name: restart sssd
  service: name=sssd state=restarted
  
- name: restart nscd
  service: name=nscd state=restarted
  
- name: restart sshd
  service: name=sshd state=restarted
  
- name: restart fail2ban
  service: name=fail2ban state=restarted

- name: restart crond
  service: name=crond state=restarted
  listen: "restart authconfig dependent"

- name: restart samba
  service: name=smb state=restarted
  
- name: restart snmpd
  service: name=snmpd state=restarted
  
- name: restart nrpe
  service: name=nrpe state=restarted

- name: restart glances
  service: name=glances state=restarted

- name: clean yum
  command: /usr/bin/yum clean all

- name: restart network
  service: name=network state=restarted
