# commit version is always avaiable, but if a tag version is found
# tag version will be used.

- name: BLUEFISH reading repository latest commit version
  local_action:
    module: shell git show | grep commit -m 1 | awk '{print $2}'
  register: bluefish_ver
  changed_when: false

- name: BLUEFISH reading the repository version from Git tag
  local_action:
    module: shell git describe
  register: bluefish_tag_ver
  changed_when: false

- set_fact:
    bluefish_ver: "{{ bluefish_tag_ver }}"
  when: bluefish_tag_ver is succeeded

- name: SERVER reading the machine vendor information from dmidecode
  shell: "/usr/sbin/dmidecode -t 1 | grep Manufacturer | awk -F ':' '{print $2}' | awk '{$1=$1};1'"
  register: vendor
  changed_when: false
  ignore_errors: true
  
- name: SERVER reading the machine model information from dmidecode
  shell: "/usr/sbin/dmidecode -t 1 | grep Product | awk -F ':' '{print $2}' | awk '{$1=$1};1'"
  register: model
  changed_when: false
  ignore_errors: true
  
- name: DEBUG printing BLUEFISH version in this execution and server information
  debug:
    msg: "BLUEFISH Version: {{ bluefish_ver.stdout }} | SERVER: {{ vendor.stdout }} {{ model.stdout }}"
  
- name: YUM install essential packages required for executing the playbook tasks
  yum:
    name:
      - expect
    state: present
    update_cache: yes
  register: yum_rc
  retries: 10
  until: yum_rc is succeeded
  delay: 5

