- name: Get the machine vendor
  shell: "/usr/sbin/dmidecode -t 1 | grep Manufacturer | awk -F ':' '{print $2}' | awk '{$1=$1};1'"
  register: vendor
  changed_when: false
  ignore_errors: true
  
- name: Get the machine model
  shell: "/usr/sbin/dmidecode -t 1 | grep Product | awk -F ':' '{print $2}' | awk '{$1=$1};1'"
  register: model
  changed_when: false
  ignore_errors: true
  
- name: What's the vendor?
  debug: var=vendor.stdout
  
- name: What's the model?
  debug: var=model.stdout

- name: YUM install essential packages required for executing the playbook tasks
  yum:
    name:
      - expect
    state: present
    update_cache: yes
  register: yum_rc
  retries: 10
  until: yum_rc is succeeded
  delay: 5

