- name: CUDA RUNFILE installing driver (no toolkit)
  command: bash {{ cuda_runfile_path }} --silent --driver

- name: CUDA installing nvidia-persistenced shell script
  template:
    src: nvidia-dev.sh.j2
    dest: /root/nvidia-dev.sh
    owner: root
    group: root
    mode: 0754

- name: rc.local enabling nvidia-persistenced shell script at boot
  lineinfile:
    path: /etc/rc.d/rc.local
    line: 'bash /root/nvidia-dev.sh'
    owner: root
    group: root
    mode: 0744
